import React, { useEffect, useRef } from 'react';
import { Message } from '../types';
import BotIcon from './icons/BotIcon';
import StarIcon from './icons/StarIcon';
import StarOutlineIcon from './icons/StarOutlineIcon';
import UserIcon from './icons/UserIcon';
import EditIcon from './icons/EditIcon';

interface FavoritesPanelProps {
  messages: Message[];
  isOpen: boolean;
  onClose: () => void;
  userProfilePicture: string | null;
  onProfilePictureChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  triggerRef: React.RefObject<HTMLButtonElement>;
}

const FavoriteMessage: React.FC<{ message: Message, userProfilePicture: string | null }> = ({ message, userProfilePicture }) => {
  const isModel = message.role === 'model';
  return (
    <div className="p-4 border-b border-rose-100">
      <div className="flex items-start gap-3">
        {isModel && (
          <div className="flex-shrink-0 w-8 h-8 rounded-full bg-rose-500 flex items-center justify-center text-white mt-1">
            <BotIcon />
          </div>
        )}
        {!isModel && (
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center mt-1 overflow-hidden">
              {userProfilePicture ? (
                <img src={userProfilePicture} alt="You" className="w-full h-full object-cover" />
              ) : (
                <UserIcon className="h-5 w-5 text-gray-600" />
              )}
            </div>
        )}
        <div className="flex-grow">
          <p className={`font-bold ${isModel ? 'text-rose-600' : 'text-gray-700'}`}>
            {isModel ? 'Luna' : 'You'}
          </p>
          <p className="text-gray-800 whitespace-pre-wrap">{message.text}</p>
          {message.imageUrl && (
            <img 
                src={message.imageUrl} 
                alt="Generated by Luna" 
                className="mt-2 rounded-lg max-w-full shadow-sm" 
            />
          )}
        </div>
      </div>
    </div>
  );
};

const FavoritesPanel: React.FC<FavoritesPanelProps> = ({ messages, isOpen, onClose, userProfilePicture, onProfilePictureChange, triggerRef }) => {
  const panelRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen) {
      // Focus the close button when the panel opens
      const closeButton = panelRef.current?.querySelector('button');
      closeButton?.focus();

      const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          onClose();
        }
        if (e.key === 'Tab') {
          const focusableElements = panelRef.current?.querySelectorAll<HTMLElement>(
            'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
          );
          if (!focusableElements) return;

          const firstElement = focusableElements[0];
          const lastElement = focusableElements[focusableElements.length - 1];

          if (e.shiftKey) {
            // If shift-tabbing from the first element, cycle to the last
            if (document.activeElement === firstElement) {
              lastElement.focus();
              e.preventDefault();
            }
          } else {
            // If tabbing from the last element, cycle to the first
            if (document.activeElement === lastElement) {
              firstElement.focus();
              e.preventDefault();
            }
          }
        }
      };

      document.addEventListener('keydown', handleKeyDown);
      return () => {
        document.removeEventListener('keydown', handleKeyDown);
        // Return focus to the trigger button when panel closes
        triggerRef.current?.focus();
      };
    }
  }, [isOpen, onClose, triggerRef]);

  const panelClasses = isOpen 
    ? "translate-x-0" 
    : "translate-x-full";

  return (
    <>
      <div 
        className={`fixed inset-0 bg-black/30 z-30 transition-opacity duration-300 ${isOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}
        onClick={onClose}
        aria-hidden="true"
      />
      <div 
        ref={panelRef}
        className={`fixed top-0 right-0 h-full w-full max-w-md bg-white shadow-2xl z-40 transform transition-transform duration-300 ease-in-out ${panelClasses}`}
        role="dialog"
        aria-modal="true"
        aria-labelledby="favorites-heading"
      >
        <div className="flex flex-col h-full">
          <header className="flex items-center justify-between p-4 border-b border-rose-200">
            <div className="flex items-center gap-2">
              <StarIcon className="text-yellow-400" />
              <h2 id="favorites-heading" className="text-xl font-bold text-gray-800">Favorite Messages</h2>
            </div>
            <button 
              onClick={onClose} 
              className="p-2 rounded-full text-gray-500 hover:bg-rose-100 hover:text-rose-500 transition-colors"
              aria-label="Close favorites panel"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </header>

          <div className="p-4 border-b border-rose-200">
            <div className="flex items-center gap-4">
              <div className="relative group flex-shrink-0">
                <div className="w-16 h-16 rounded-full bg-gray-300 flex items-center justify-center overflow-hidden shadow-md">
                   {userProfilePicture ? (
                    <img src={userProfilePicture} alt="Your profile" className="w-full h-full object-cover" />
                  ) : (
                    <UserIcon className="w-10 h-10 text-gray-500" />
                  )}
                </div>
                <label 
                  htmlFor="profile-pic-upload"
                  className="absolute inset-0 bg-black/40 rounded-full flex items-center justify-center text-white opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer"
                  aria-label="Change profile picture"
                >
                  <EditIcon />
                </label>
                <input 
                  id="profile-pic-upload" 
                  type="file" 
                  className="hidden" 
                  onChange={onProfilePictureChange} 
                  accept="image/png, image/jpeg" 
                />
              </div>
              <div>
                <h3 className="font-bold text-lg text-gray-800">You</h3>
                <p className="text-sm text-gray-600">Your cherished memories</p>
              </div>
            </div>
          </div>

          <div className="flex-grow overflow-y-auto">
            {messages.length > 0 ? (
              <div>
                {messages.map(msg => <FavoriteMessage key={msg.id} message={msg} userProfilePicture={userProfilePicture} />)}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-full text-center p-8">
                <StarOutlineIcon className="w-16 h-16 text-gray-300 mb-4" />
                <h3 className="text-lg font-semibold text-gray-700">No Favorites Yet</h3>
                <p className="text-gray-500">Click the star on a message to save your most cherished moments here.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default FavoritesPanel;